name: Actions Workflow

on:
  push:
    branches:
      - master
      - "feature/*" # matches feature/featA but not feature/feat/A
      - "feature/**" # matches feature/feat/A
      - "!feature/featC"
    tags:
      - v1.*
    # paths:
    #   - '**.js' # only run when a js-file changes
    #   - '!filename.js'
    paths-ignore:
      - "docs/**" # don't run on changes in docs
  # repository_dispatch:
  #   types: [build]
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  #push:
  # pull_request:
  #   types: [closed, assigned, opened, reopened]
  # GITHUB_SSH = commit id
  # GITHUB_REF = bransh
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "{{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: George
      - name: Log Greeting Time
        run: echo "{{ steps.greet.outputs.time }}"
